### ISSUE TITLE
How to process CDATA in `toVdom`

### ISSUE THREAD

**Issue by luisherranz** [luisherranz/block-hydration-experiments#109]
We've found some websites that have `CDATA` sections. One of them is https://www.tiens-donc.com/. I think @santosguillamot has more.

We need to decide what to do with those nodes. Maybe the first thing to investigate is what does Preact with them. Does it delete them? (as it does with the HTML comments)

I'm just opening the issue, so this is documented, but happy to see someone else take over on this 🙂

**Comment by DAreRodz** [comment]
According to the [MDN web docs](https://developer.mozilla.org/en-US/docs/Web/API/CDATASection):

> CDATA sections should not be used within HTML they are considered as comments and not displayed.

I would expect them to be comments (i.e., `nodeType = 8`), but you are right [here](https://github.com/WordPress/block-hydration-experiments/pull/107#issuecomment-1330915605): the CDATA sections have a different node type. 😓



> Maybe the first thing to investigate is what does Preact with them. Does it delete them? (as it does with the HTML comments)

I guess they don't even consider that case because you can't render CDATA sections with Preact. 🤷 In any case, I would treat them as comments if that's what browsers do.

**Comment by SantosGuillamot** [comment]
>We've found some websites that have CDATA sections. One of them is https://www.tiens-donc.com/. I think @SantosGuillamot has more.

The only one I found apart from the one you mention is [yourcontentempire.com](https://href.li/?http://yourcontentempire.com/).

>Maybe the first thing to investigate is what does Preact with them. Does it delete them?

The only mention to CDATA in preact repo was [this Pull Request](https://github.com/preactjs/preact/pull/3337), which makes me think they treat CDATA the same way they treat comments. However, I don't know how to check that, I'm not familiar with their code.

**Comment by SantosGuillamot** [comment]
I also found [this other issue ](https://github.com/facebook/react/issues/22518) in React repo talking about CDATA in SVGs.

I've been taking a look, and it seems it was a recommended way of adding style to SVGs (not sure if it still is). Moreover, if I navigate to one of the SVGs in [tiens-donc.com](https://www.tiens-donc.com/) (the Design grapiqhe logo at the footer) and remove the CDATA part, the style changes. On the other hand, pasting our script in the console, it removes the CDATA part, but it doesn't affect the style.

If this is something common, and we can affect the layout of the page, I wouldn't feel comfortable just ignoring them.

**Comment by DAreRodz** [comment]
Thanks for digging up into this, @SantosGuillamot. 😊 I haven't thought that [SVG is written in XML](https://www.w3.org/TR/SVG11/intro.html#:~:text=SVG%20is%20a%20language%20for%20describing%20two%2Ddimensional%20graphics%20in%20XML%20%5BXML10%5D.), and CDATA sections are indeed part of the XML syntax.

Maybe preact handles SVG nodes differently; I'd have to read the code to be sure, though.

**Comment by luisherranz** [comment]
There are a lot of plugins using CDATA: https://wpdirectory.net/search/01GK6KA61J97BER8RQCTDFP57G

**Comment by DAreRodz** [comment]
I've been taking a closer look at the issue, and I think we can safely convert the `CDATASection` nodes into `Text` nodes.

This is what I have found so far:

- The `<![CDATA[...]]>` syntax is not allowed in HTML documents **_except_** inside foreign elements (SVG and MathML) (see [this](https://html.spec.whatwg.org/#cdata-sections:~:text=CDATA%20sections%20can%20only%20be%20used%20in%20foreign%20content%20(MathML%20or%20SVG).)). If the HTML parser finds a `CDATA` section, it is transformed into a `Comment` node in the first case and into a `Text` node containing the value inside the brackets in the second one.
   
  This happens whenever HTML code is parsed (e.g., initial render, changing the HTML through `innerHTML`, parsing a document with `DOMParser`, etc.).

   For example, the following code

  ```js
   const html = `
  <body>
    <![CDATA[This will be a comment]]>
    <svg viewBox="0 0 300 100">
      <style>
        <![CDATA[circle { stroke: red; fill: grey; }]]>
      </style>
      <circle cx="50" cy="50" r="40" />
    </svg>
  </body>
  `;
  
  new DOMParser()
    .parseFromString(html, 'text/html')
    .querySelector('body')
  ```

   outputs this HTML

  ```html
  <body>
    <!--[CDATA[This will be a comment]]-->
    <svg viewBox="0 0 300 100">
      <style>
        circle { stroke: red; fill: grey; }
      </style>
      <circle cx="50" cy="50" r="40"></circle>
    </svg>
  </body>
  ```
- The `CDATASection` nodes that appear in tested sites (e.g., https://www.tiens-donc.com/) come from `.svg` files parsed using `image/svg+xml` instead of `text/html` as the `mimeType`. The code is something similar to this:
  
  ```js
  document.querySelectorAll('img.svg').forEach(async (img) => {
    const res = await fetch(img.src);
    const nodes = new DOMParser(await res.text(), 'image/svg+xml').childNodes;
    img.replaceWith(nodes);
  });
  ```

  That means `CDATASection` nodes only appear in runtime when they are instantiated and then added to the DOM tree, not while parsing HTML code. In any case, if that happens, we could detect if the `CDATASection` node is inside a foreign element (which would probably be the case) and transform it into a `Text` node right before hydration, or remove it otherwise, like `Comment` nodes.

**Comment by DAreRodz** [comment]
Tentative fix, assuming `CDATASection` nodes are always inside foreign elements:

```diff
diff --git a/src/runtime/vdom.js b/src/runtime/vdom.js
index 22894a5..d20bf05 100644
--- a/src/runtime/vdom.js
+++ b/src/runtime/vdom.js
@@ -7,6 +7,7 @@ export default function toVdom(node) {
 	const wpDirectives = {};
 	let hasWpDirectives = false;
 
+	if (node.nodeType === 4) node.replaceWith(new Text(node.nodeValue));
 	if (node.nodeType === 3) return node.data;
 
 	for (let i = 0; i < attributes.length; i++) {

```

**Comment by DAreRodz** [comment]
I'm pretty sure we can use the fix above for every case. It looks like if a `CDATASection` node appears anywhere in an HTML tree, it is rendered like a `Text` node.

You can try using the following script (tested in Chrome):

```js
document.body.appendChild(
  ...new DOMParser()
    .parseFromString("<svg><![CDATA[hi there]]></svg>", "image/svg+xml")
    .querySelector("svg").childNodes
);
```

PS: Funny thing, if you try to instantiate a `CDATASection` using `new`, you get an `Illegal constructor` error.

**Comment by SantosGuillamot** [comment]
Thanks a lot for the triage David! 🙂 

> Tentative fix, assuming CDATASection nodes are always inside foreign elements:

I've tried it in the sites we were facing this issue ([tiens-donc.com](https://www.tiens-donc.com/) for ex.), and I'm still getting the same error because `attributes` is `undefined`.

~~If I print the node without attributes in the console, it seems it is already a text node with `node.nodeType = 3`.~~ Nevermind, this is because I was doing the check before the `if (node.nodeType === 3) return node.data`. But it still returns the same error.

**Comment by DAreRodz** [comment]
> I've tried it in the sites we were facing this issue ([tiens-donc.com](https://www.tiens-donc.com/) for ex.), and I'm still getting the same error because `attributes` is `undefined`.

Oops, my fault. Thanks for reporting, @SantosGuillamot; I thought `replaceWith` would modify the object pointed by the `node` variable, but it still holds a reference to the original node (I should have tested the changes before posting 😅).

Second tentative fix:

```diff
diff --git a/src/runtime/vdom.js b/src/runtime/vdom.js
index 22894a5..28c0714 100644
--- a/src/runtime/vdom.js
+++ b/src/runtime/vdom.js
@@ -7,6 +7,11 @@ export default function toVdom(node) {
 	const wpDirectives = {};
 	let hasWpDirectives = false;
 
+	if (node.nodeType === 4) {
+		node.replaceWith(new Text(node.nodeValue));
+		return node.nodeValue;
+	}
+
 	if (node.nodeType === 3) return node.data;
 
 	for (let i = 0; i < attributes.length; i++) {

```

**Comment by SantosGuillamot** [comment]
Okay, that seems to work fine. Thanks David!

To clarify, with this change, we will still have a mutation, but it shouldn't affect the layout. I'm sharing the removed node and the added node.

_Removed node_
```html
<svg ...>
    <style type="text/css">
	<![CDATA[
	    .st0{fill:#FFFFFF;}
	    .st1{fill:#070707;}
        ]]>
    </style>
    <g>...</g>
</sv>
```

_Added node_
```html
<svg ...>
    <style type="text/css">
	.st0{fill:#FFFFFF;}
	.st1{fill:#070707;}
    </style>
    <g>...</g>
</sv>
```

It seems we shouldn't worry about this change because the wrapper `<![CDATA[` is to escape characters in XML. It isn't needed in HTML. I've tested the same SVGs with and without the wrapper, and the styles are still applied.

**Comment by SantosGuillamot** [comment]
I created a PR with this proposal https://github.com/WordPress/block-hydration-experiments/pull/115. I also reverted https://github.com/WordPress/block-hydration-experiments/pull/107 now that it seems we can handle CDATA properly.

**Comment by DAreRodz** [comment]
> It seems we shouldn't worry about this change because the wrapper `<![CDATA[` is to escape characters in XML. It isn't needed in HTML. I've tested the same SVGs with and without the wrapper, and the styles are still applied.

Yup, I think the same (it's what browsers do, actually). In any case, `CDATASection` nodes are not allowed in HTML documents, and HTML parsers transform them into either comments or text nodes, depending on the context.

**Comment by SantosGuillamot** [comment]
As we have merged https://github.com/WordPress/block-hydration-experiments/pull/115, I'm closing this issue. Feel free to reopen it if you believe there are more decisions to take or if we should follow another approach.

**Comment by luisherranz** [comment]
Thanks, folks. We need to remember to add e2e tests for all these use cases.
