### ISSUE TITLE
Documentation: Nobody ever says what directives are

### ISSUE THREAD

**Issue by tomjn** [luisherranz/block-hydration-experiments#129]
I've come here from the Make WP post, but both that post, this repo, and all the issues have this problem.

The goal of the project to make building interactive blocks easier is well stated, but none of the experiments or attempts to achieve that are explained, and they're all referred to by their terminology which is never explained. 

For example, neither the Make post, the readme, or the main tracking issue ever says what directives are. This is the closest anybody gets to explaining what directives are:

> The goal is to create an installable plugin that adds a set of basic directives and client-side transitions to any site.

_But what are directives?_ And thanks to anybody who tries to explain in this issue, but it needs adding to the readme.

The repo is named after hydration experiments, and that gives some clues based on some articles I read a long time ago about React server side rendering and rehydrating components in the browser, but that too is unclear in the context of this project and blocks. I might interpret this as allowing you to build both the editor and frontend interfaces in React, but what I've read elsewhere doesn't fit this interpretation.

**My fear is that this project is doing great work but has failed to explain what it's doing, and couched itself in opaque terminology.** There are no examples or use cases in the readme, no screenshots or videos, no glossary, etc. I should have been able to tell what these things were within 30 seconds via the readme.

**Comment by justintadlock** [comment]
I also replied to this [in the comments](https://make.wordpress.org/core/2023/01/11/update-on-the-work-to-make-building-interactive-blocks-easier/#comment-44285) on the Make Core post.  We definitely need more thorough explanations of what this project is doing, more so that we can bring other developers along for the journey.

Directives are special HTML attributes that allow developers to add interactivity to their markup.  A simple example might be using a `wp-show` directive:

```html
<div wp-show="state.shouldShow">content</div>
```

In this example, the inner content would only show if `state.shouldShow` is `true` or not if `false`.

This is similar to other JavaScript frameworks like Angular, Vue, and Alpine but will have some differences that will be explained when the proposal is made public.
