### ISSUE TITLE
Make sure inner blocks are sent to the frontend even if the Save/View component doesn't render them initially

### ISSUE THREAD

**Issue by DAreRodz** [luisherranz/block-hydration-experiments#59]
Right now, when inner blocks are hidden in the editor, they are not serialized and stored in the WP database, so that information is lost. Thus, the block cannot interactively show inner blocks later in the browser.

There were some previous attempts to solve this by adding a `<template>` tag.

- https://github.com/WordPress/block-hydration-experiments/pull/8

However, we removed the `<template>` tag on #28 (see https://github.com/WordPress/block-hydration-experiments/pull/28/commits/fc6fa92f96f0e60f093605449c45d4157927b3c1).

Related to https://github.com/WordPress/block-hydration-experiments/issues/29.

**Comment by luisherranz** [comment]
Should we try to do this in the Gutenberg repo instead? Maybe in the [serializer](https://github.com/WordPress/gutenberg/blob/trunk/packages/element/src/serialize.js)? I'm not sure if it makes sense to do it in _user land_ when it won't be necessary...

**Comment by luisherranz** [comment]
For anyone interested in taking a look at this, I think that what needs to happen is:

![image](https://user-images.githubusercontent.com/3305402/186853188-6ecf0057-593b-4de3-b387-749cbf33b330.png)

[Excalidraw](https://excalidraw.com/#json=QscBFTeWkWB3pqg-H0U7Y,Lwr7Db16H6V9tOUojlqBoQ)

Non-interactive blocks don't need this because those "hidden" inner blocks won't ever be shown, and therefore they don't need to be sent to the client.

**Comment by luisherranz** [comment]
Closed as we're not actively working on this experiment anymore and this works fine in the Directives Hydration.
